config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  resources :rs_as

  post '/rsas' => 'rs_as#new'
  get '/rsas/:id' => 'rs_as#show'
  post '/rsas/:id/encrypt_messages' => 'tweets#new'
  get '/rsas/:id/encrypt_messages/:msgid' => 'tweets#show'
  post '/rsas/:id/decrypt_messages' => 'tweets#decrypt'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rsas.rb
class Rsas < ApplicationRecord
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rs_as_controller.rb
class RsAsController < ApplicationController
  before_action :set_rsa, only: [:show, :edit, :update, :destroy]

  # GET /rsas
  # GET /rsas.json
  def index
    @rsas = Rsas.all
  end

  # GET /rsas/1
  # GET /rsas/1.json
  def show
	rsa = Rsas.find_by id: params[:id]
	render json: {n: @rsa.n, e: @rsa.e, d: @rsa.d}
  end

  # GET /rsas/new
  def new
    @rsas = Rsas.new
  end

  # GET /rsas/1/edit
  def edit
  end

  # POST /rsas
  # POST /rsas.json
  def create
    if(params.has_key?(:n) && params.has_key?(:e) && params.has_key?(:d)) then
			@rsas = Rsas.new(n: params[:n],e: params[:e],d: params[:d])
	else
			key = Array.new
			num = 1000
			q = rand(num)
			p = rand(num)
			while(1) do 
				q = rand(num)
				p = rand(num)
				if Prime.prime?(p) && Prime.prime?(q) then
					break
				end
			end
		
			n = p*q
			fiofn = (p-1)*(q-1)
			e = rand(num)
		
			while(1) do
				e = rand(num)
				if e != Prime.prime_division(n) && 1 < e && e < fiofn then
					break
				end
			end
			k = 2
	 		d = 1 + (k*fiofn)/e
	
			key[0] = n
			key[1] = e
			key[2] = d
		
			@rsas = Rsas.new(n:key[0],e:key[1],d:key[2])
			@rsas.save
	
		end
    
  end

  # PATCH/PUT /rsas/1
  # PATCH/PUT /rsas/1.json
  def update
    respond_to do |format|
      if @rsa.update(rsa_params)
        format.html { redirect_to @rsa, notice: 'Rsas was successfully updated.' }
        format.json { render :show, status: :ok, location: @rsa }
      else
        format.html { render :edit }
        format.json { render json: @rsa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rsas/1
  # DELETE /rsas/1.json
  def destroy
    @rsa.destroy
    respond_to do |format|
      format.html { redirect_to rsas_index_url, notice: 'Rsas was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rsa
      @rsa = Rsas.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rsa_params
     params.require(:rsas).permit(:n, :e, :d)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
	twt = Tweet.find_by id: params[:id], rid: params[:rid]
render.json: {'twt' => twt.content}
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
	def create
    	rsa = Rsa.find_by id: params[:id]

	encrypted = (params[:tweet].chars.map {|c| c.ord ** @e % @n}).join(",")
	twt = Tweet.new({rid: rsa.id, content: encrypted})
		if(twt.save)
			render.json: {'id' => twt.id}
		end
	end
	
def decrypt
		rsa = Rsa.find_by id: params[:id]

		decrypted = (params[:tweet].split(",").map {|c| (c.to_i ** @d % @n).chr}).join("")
		render.json: {'content' => decrypted}
	end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
       params.require(:tweets).permit(:content, :id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rs_as_helper.rb
module RsAsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rsawebv1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rs_as/_form.html.erb
<%= form_with(model: rsa, local: true) do |form| %>
  <% if rsa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rsa.errors.count, "error") %> prohibited this rsa from being saved:</h2>

      <ul>
      <% rsa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rs_as/edit.html.erb
<h1>Editing Rsa</h1>

<%= render 'form', rsa: @rsa %>

<%= link_to 'Show', @rsa %> |
<%= link_to 'Back', rsas_index_path %>

app/views/rs_as/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rsas</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rsas.each do |rsa| %>
      <tr>
        <td><%= link_to 'Show', rsa %></td>
        <td><%= link_to 'Edit', edit_rsa_path(rsa) %></td>
        <td><%= link_to 'Destroy', rsa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rsa', new_rsa_path %>

app/views/rs_as/new.html.erb
<h1>New Rsa</h1>

<%= render 'form', rsa: @rsa %>

<%= link_to 'Back', rsas_index_path %>

app/views/rs_as/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_rsa_path(@rsa) %> |
<%= link_to 'Back', rsas_index_path %>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>